### ISSUE TITLE
Save image with filter 

### ISSUE THREAD

**Issue by ziacto** [hardik-trivedi/FaceFilter#1]
can you write the code for saving the image and put a mask on face. I have tried with your code but only able to save the pic with wrong orientation. Here is code but i can not get the mask. Can you help me out. Thanks

findViewById(R.id.button2).setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    mCameraSource.takePicture(null, new CameraSource.PictureCallback() {
                        private File imageFile;

                        @Override
                        public void onPictureTaken(byte[] bytes) {
                            try {
                                // convert byte array into bitmap
                                Bitmap loadedImage = null;

                                loadedImage = BitmapFactory.decodeByteArray(bytes, 0,
                                        bytes.length);

                                Bitmap bitmap = Bitmap.createBitmap(loadedImage, 0, 0, loadedImage.getWidth(), loadedImage.getHeight());

                                dir = new File(
                                        Environment.getExternalStoragePublicDirectory(
                                                Environment.DIRECTORY_PICTURES), "MyPhotos");

                                boolean success = true;
                                if (!dir.exists())
                                {
                                    try {
                                        success = dir.mkdirs();
                                    }catch (Exception e){
                                        Toast.makeText(getBaseContext(),e.getMessage() + " "+ e.getCause(),
                                                Toast.LENGTH_SHORT).show();
                                    }

                                }
                                if (success) {
                                    java.util.Date date = new java.util.Date();
                                    imageFile = new File(dir.getAbsolutePath()
                                            + File.separator
                                            + new Timestamp(date.getTime()).toString()
                                            + "Image.jpg");

                                    imageFile.createNewFile();
                                } else {
                                    Toast.makeText(getBaseContext(), "Image Not saved",
                                            Toast.LENGTH_SHORT).show();
                                    return;
                                }
                                ByteArrayOutputStream ostream = new ByteArrayOutputStream();

                                // save image into gallery
                                bitmap.compress(Bitmap.CompressFormat.JPEG, 100, ostream);

                                FileOutputStream fout = new FileOutputStream(imageFile);
                                fout.write(ostream.toByteArray());
                                fout.close();
                                ContentValues values = new ContentValues();

                                values.put(MediaStore.Images.Media.DATE_TAKEN,
                                        System.currentTimeMillis());
                                values.put(MediaStore.Images.Media.MIME_TYPE, "image/jpeg");
                                values.put(MediaStore.MediaColumns.DATA,
                                        imageFile.getAbsolutePath());

                                FaceFilterActivity.this.getContentResolver().insert(
                                        MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);

                                loadedImage = overlay(bitmap,loadBitmapFromView(mGraphicOverlay));
                                loadedImage =RotateBitmap(loadedImage,90);
                                saveToInternalStorage(loadedImage);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    });
                }
            });

**Comment by hardik-trivedi** [comment]
Try to check ExifInterface http://stackoverflow.com/questions/20478765/how-to-get-the-correct-orientation-of-the-image-selected-from-the-default-image.

**Comment by SajidAguero2110** [comment]
@hardik-trivedi The link you shared is for orientation purpose.. In general I am unable to save the overlay image on camera source. I have tried merging both bitmaps but still it does not work.

**Comment by josecarlos3390** [comment]
hello, you can take screenshot to the mask and the camera image ? i can't :(
